server:
  port: 8043
spring:
  application:
    name: myEurka-server
  security:
    user:
      name: yjt
      password: 123456
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/